# Example docker compose config.

services:
  shairport-sync:
    image: mikebrady/shairport-sync:latest # With ALSA
    #image: mikebrady/shairport-sync:latest-pa # With PulseAudio
    network_mode: host
    restart: unless-stopped
    # For PulseAudio
    #environment:
    #  PULSE_SERVER: unix:/tmp/pulseaudio.socket
    #  PULSE_COOKIE: /tmp/pulseaudio.cookie
    # For ALSA if not using config/autodetect fails, adjust as needed
    #command: [ "-o", "alsa", "--", "-d", "hw:0", "-c", "Headphone" ]
    devices:
      - "/dev/snd"
    # volumes:
    #   - ../scripts/shairport-sync/shairport-sync.conf:/etc/shairport-sync.conf # Customised Shairport Sync configuration file.
    #   - /run/user/1000/pulse/native:/tmp/pulseaudio.socket # PulseAudio: socket
    #   - ./pulseaudio.client.conf:/etc/pulse/client.conf # PulseAudio: client-config
    logging:
      options:
        max-size: "200k"
        max-file: "10"
